import onnx
from mmdnn.conversion.onnx.onnx_polish import *


def save_model(MainModel, network_filepath, weight_filepath, dump_filepath):
    from mmdnn.conversion.onnx.polish import onnx_polish
    model = MainModel.KitModel(weight_filepath)
    onnx_polish(model)
    onnx.save(model, dump_filepath)    
    print('ONNX model file is saved as [{}], generated by [{}.py] and [{}].'.format(
        dump_filepath, network_filepath, weight_filepath))
